levels = {
    1: [
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rCwwwwwwwwwwwwwy",
        "       h           rwwwwwwwwwwwwwwy",
        "      ---  ---     rwwwwwwwwwwwwwwy",
        "      s    s    k  RRRRRRRRRRRRRRRy",
        "   c           -- Srwwwwwwwwwwwwwwy",
        "  ---              rwiwwiwwiwwiwwiy",
        "                   rwIwwIwwIwwIwwIy",
        "      c c     tg   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "___________________________________",
        "==================================="],
    2: [
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rCwwwwwwwwwwwwwy",
        "           k       rwwwwwwwwwwwwwwy",
        "         ----- g   rwwwwwwwwwwwwwwy",
        "       -  s     c  RRRRRRRRRRRRRRRy",
        "    c          -- Srwwwwwwwwwwwwwwy",
        "   ---P            rwiwwiwwiwwiwwiy",
        "                   rwIwwIwwIwwIwwIy",
        "     t  c          rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "___________________________________",
        "==================================="],
    3: [
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rCwwwwwwwwwwwwwy",
        " k                 rwwwwwwwwwwwwwwy",
        "--         --- g   rwwwwwwwwwwwwwwy",
        "      -- g      c  RRRRRRRRRRRRRRRy",
        "   c           -- Srwwwwwwwwwwwwwwy",
        "   --              rwiwwiwwiwwiwwiy",
        "                   rwIwwIwwIwwIwwIy",
        "     t  c    g     rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "___________________________________",
        "==================================="],
    4: [
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rCwwwwwwwwwwwwwy",
        "         f         rwwwwwwwwwwwwwwy",
        "         k         rwwwwwwwwwwwwwwy",
        "        ---        RRRRRRRRRRRRRRRy",
        " g   -       -   gSrwwwwwwwwwwwwwwy",
        "         x         rwiwwiwwiwwiwwiy",
        "---             ---rwIwwIwwIwwIwwIy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "___________________________________",
        "==================================="],
    5: [
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rCwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "         --        rwwwwwwwwwwwwwwy",
        "      -     gg hc  RRRRRRRRRRRRRRRy",
        " c             -- Srwwwwwwwwwwwwwwy",
        "  --        c      rwiwwiwwiwwiwwiy",
        "     g             rwIwwIwwIwwIwwIy",
        "                   rwwwwwwwwwwwwwwy",
        " kg     F     F    rwwwwwwwwwwwwwwy",
        "____bmmmmmmmmmmmmd_________________",
        "====WWWWWWWWWWWWWW================="],
    6: [
        "                   rwwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "                   rCwwwwwwwwwwwwwy",
        "                   rwwwwwwwwwwwwwwy",
        "         --        rwwwwwwwwwwwwwwy",
        "      -     gg hc  RRRRRRRRRRRRRRRy",
        " c      М      -- Srwwwwwwwwwwwwwwy",
        "  --        c      rwiwwiwwiwwiwwiy",
        "     g             rwIwwIwwIwwIwwIy",
        "                   rwwwwwwwwwwwwwwy",
        " kg                rwwwwwwwwwwwwwwy",
        "___________________________________",
        "==================================="],
}

levels_themes = {
    1: "grass",
    2: "grass",
    3: "grass",
    4: "grass",
    5: "grass",
    6: "ice"
}
